"$schema" = "./node_modules/wrangler/config-schema.json"
name = "think"
compatibility_date = "2026-05-10"
compatibility_flags = ["nodejs_compat"]

main = "./src/server.ts"

[placement]
mode = "smart"

[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = true
head_sampling_rate = 1

[vars]
POLICY_AUD = "297465c25a8782649ded486831360fdf0ad8e23d0165d35243617198c59d702a"
TEAM_DOMAIN = "https://luqi.cloudflareaccess.com"
AI_GATEWAY_ID = "think"
AI_GATEWAY_MODEL = "@cf/moonshotai/kimi-k2.6"

[ai]
binding = "AI"

[assets]
not_found_handling = "single-page-application"

[durable_objects]
bindings = [{ name = "MyAgent", class_name = "MyAgent" }]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["MyAgent"]
